version: "3"
services:
  snipe-it:
    container_name: snipeitserver
    image: snipe/snipe-it:latest
    restart: always
    volumes:
    - snipeit:/var/lib/snipeit
    - snipeit-logs:/var/www/html/storage/logs

    volumes:
    snipeit:
      external: true
    snipeit-logs:
      external: true